version: '3.8'

services:
  sql:
    image: dominikpietek/sql
    ports:
      - "1433:1433"
    networks:
      - app-network
    environment:
      SA_PASSWORD: "P4ssw0rd"
      ACCEPT_EULA: "Y"
  orderfoodapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
