version: '3.8'

services:
  sql3:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "123Domis@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
  OrderFoodApi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql-server
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
